// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocol.proto

package ru.ifmo.java.task.protocol;

public final class Protocol {
  private Protocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ru.ifmo.java.task.protocol.Request)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 size = 1;</code>
     * @return The size.
     */
    int getSize();

    /**
     * <code>repeated int32 elem = 2;</code>
     * @return A list containing the elem.
     */
    java.util.List<java.lang.Integer> getElemList();
    /**
     * <code>repeated int32 elem = 2;</code>
     * @return The count of elem.
     */
    int getElemCount();
    /**
     * <code>repeated int32 elem = 2;</code>
     * @param index The index of the element to return.
     * @return The elem at the given index.
     */
    int getElem(int index);
  }
  /**
   * Protobuf type {@code ru.ifmo.java.task.protocol.Request}
   */
  public  static final class Request extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ru.ifmo.java.task.protocol.Request)
      RequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Request.newBuilder() to construct.
    private Request(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Request() {
      elem_ = emptyIntList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Request();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Request(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              size_ = input.readInt32();
              break;
            }
            case 16: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                elem_ = newIntList();
                mutable_bitField0_ |= 0x00000001;
              }
              elem_.addInt(input.readInt32());
              break;
            }
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) != 0) && input.getBytesUntilLimit() > 0) {
                elem_ = newIntList();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                elem_.addInt(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          elem_.makeImmutable(); // C
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ru.ifmo.java.task.protocol.Protocol.internal_static_ru_ifmo_java_task_protocol_Request_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ru.ifmo.java.task.protocol.Protocol.internal_static_ru_ifmo_java_task_protocol_Request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ru.ifmo.java.task.protocol.Protocol.Request.class, ru.ifmo.java.task.protocol.Protocol.Request.Builder.class);
    }

    public static final int SIZE_FIELD_NUMBER = 1;
    private int size_;
    /**
     * <code>int32 size = 1;</code>
     * @return The size.
     */
    public int getSize() {
      return size_;
    }

    public static final int ELEM_FIELD_NUMBER = 2;
    private com.google.protobuf.Internal.IntList elem_;
    /**
     * <code>repeated int32 elem = 2;</code>
     * @return A list containing the elem.
     */
    public java.util.List<java.lang.Integer>
        getElemList() {
      return elem_;
    }
    /**
     * <code>repeated int32 elem = 2;</code>
     * @return The count of elem.
     */
    public int getElemCount() {
      return elem_.size();
    }
    /**
     * <code>repeated int32 elem = 2;</code>
     * @param index The index of the element to return.
     * @return The elem at the given index.
     */
    public int getElem(int index) {
      return elem_.getInt(index);
    }
    private int elemMemoizedSerializedSize = -1;

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (size_ != 0) {
        output.writeInt32(1, size_);
      }
      if (getElemList().size() > 0) {
        output.writeUInt32NoTag(18);
        output.writeUInt32NoTag(elemMemoizedSerializedSize);
      }
      for (int i = 0; i < elem_.size(); i++) {
        output.writeInt32NoTag(elem_.getInt(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (size_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, size_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < elem_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(elem_.getInt(i));
        }
        size += dataSize;
        if (!getElemList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        elemMemoizedSerializedSize = dataSize;
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ru.ifmo.java.task.protocol.Protocol.Request)) {
        return super.equals(obj);
      }
      ru.ifmo.java.task.protocol.Protocol.Request other = (ru.ifmo.java.task.protocol.Protocol.Request) obj;

      if (getSize()
          != other.getSize()) return false;
      if (!getElemList()
          .equals(other.getElemList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SIZE_FIELD_NUMBER;
      hash = (53 * hash) + getSize();
      if (getElemCount() > 0) {
        hash = (37 * hash) + ELEM_FIELD_NUMBER;
        hash = (53 * hash) + getElemList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ru.ifmo.java.task.protocol.Protocol.Request parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ru.ifmo.java.task.protocol.Protocol.Request parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ru.ifmo.java.task.protocol.Protocol.Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ru.ifmo.java.task.protocol.Protocol.Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ru.ifmo.java.task.protocol.Protocol.Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ru.ifmo.java.task.protocol.Protocol.Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ru.ifmo.java.task.protocol.Protocol.Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ru.ifmo.java.task.protocol.Protocol.Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ru.ifmo.java.task.protocol.Protocol.Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ru.ifmo.java.task.protocol.Protocol.Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ru.ifmo.java.task.protocol.Protocol.Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ru.ifmo.java.task.protocol.Protocol.Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ru.ifmo.java.task.protocol.Protocol.Request prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ru.ifmo.java.task.protocol.Request}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ru.ifmo.java.task.protocol.Request)
        ru.ifmo.java.task.protocol.Protocol.RequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ru.ifmo.java.task.protocol.Protocol.internal_static_ru_ifmo_java_task_protocol_Request_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ru.ifmo.java.task.protocol.Protocol.internal_static_ru_ifmo_java_task_protocol_Request_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ru.ifmo.java.task.protocol.Protocol.Request.class, ru.ifmo.java.task.protocol.Protocol.Request.Builder.class);
      }

      // Construct using ru.ifmo.java.task.protocol.Protocol.Request.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        size_ = 0;

        elem_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ru.ifmo.java.task.protocol.Protocol.internal_static_ru_ifmo_java_task_protocol_Request_descriptor;
      }

      @java.lang.Override
      public ru.ifmo.java.task.protocol.Protocol.Request getDefaultInstanceForType() {
        return ru.ifmo.java.task.protocol.Protocol.Request.getDefaultInstance();
      }

      @java.lang.Override
      public ru.ifmo.java.task.protocol.Protocol.Request build() {
        ru.ifmo.java.task.protocol.Protocol.Request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ru.ifmo.java.task.protocol.Protocol.Request buildPartial() {
        ru.ifmo.java.task.protocol.Protocol.Request result = new ru.ifmo.java.task.protocol.Protocol.Request(this);
        int from_bitField0_ = bitField0_;
        result.size_ = size_;
        if (((bitField0_ & 0x00000001) != 0)) {
          elem_.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.elem_ = elem_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ru.ifmo.java.task.protocol.Protocol.Request) {
          return mergeFrom((ru.ifmo.java.task.protocol.Protocol.Request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ru.ifmo.java.task.protocol.Protocol.Request other) {
        if (other == ru.ifmo.java.task.protocol.Protocol.Request.getDefaultInstance()) return this;
        if (other.getSize() != 0) {
          setSize(other.getSize());
        }
        if (!other.elem_.isEmpty()) {
          if (elem_.isEmpty()) {
            elem_ = other.elem_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureElemIsMutable();
            elem_.addAll(other.elem_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ru.ifmo.java.task.protocol.Protocol.Request parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ru.ifmo.java.task.protocol.Protocol.Request) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int size_ ;
      /**
       * <code>int32 size = 1;</code>
       * @return The size.
       */
      public int getSize() {
        return size_;
      }
      /**
       * <code>int32 size = 1;</code>
       * @param value The size to set.
       * @return This builder for chaining.
       */
      public Builder setSize(int value) {
        
        size_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 size = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSize() {
        
        size_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.Internal.IntList elem_ = emptyIntList();
      private void ensureElemIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          elem_ = mutableCopy(elem_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated int32 elem = 2;</code>
       * @return A list containing the elem.
       */
      public java.util.List<java.lang.Integer>
          getElemList() {
        return ((bitField0_ & 0x00000001) != 0) ?
                 java.util.Collections.unmodifiableList(elem_) : elem_;
      }
      /**
       * <code>repeated int32 elem = 2;</code>
       * @return The count of elem.
       */
      public int getElemCount() {
        return elem_.size();
      }
      /**
       * <code>repeated int32 elem = 2;</code>
       * @param index The index of the element to return.
       * @return The elem at the given index.
       */
      public int getElem(int index) {
        return elem_.getInt(index);
      }
      /**
       * <code>repeated int32 elem = 2;</code>
       * @param index The index to set the value at.
       * @param value The elem to set.
       * @return This builder for chaining.
       */
      public Builder setElem(
          int index, int value) {
        ensureElemIsMutable();
        elem_.setInt(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 elem = 2;</code>
       * @param value The elem to add.
       * @return This builder for chaining.
       */
      public Builder addElem(int value) {
        ensureElemIsMutable();
        elem_.addInt(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 elem = 2;</code>
       * @param values The elem to add.
       * @return This builder for chaining.
       */
      public Builder addAllElem(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureElemIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, elem_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 elem = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearElem() {
        elem_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ru.ifmo.java.task.protocol.Request)
    }

    // @@protoc_insertion_point(class_scope:ru.ifmo.java.task.protocol.Request)
    private static final ru.ifmo.java.task.protocol.Protocol.Request DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ru.ifmo.java.task.protocol.Protocol.Request();
    }

    public static ru.ifmo.java.task.protocol.Protocol.Request getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Request>
        PARSER = new com.google.protobuf.AbstractParser<Request>() {
      @java.lang.Override
      public Request parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Request(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Request> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Request> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ru.ifmo.java.task.protocol.Protocol.Request getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ru.ifmo.java.task.protocol.Response)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 size = 1;</code>
     * @return The size.
     */
    int getSize();

    /**
     * <code>repeated int32 elem = 2;</code>
     * @return A list containing the elem.
     */
    java.util.List<java.lang.Integer> getElemList();
    /**
     * <code>repeated int32 elem = 2;</code>
     * @return The count of elem.
     */
    int getElemCount();
    /**
     * <code>repeated int32 elem = 2;</code>
     * @param index The index of the element to return.
     * @return The elem at the given index.
     */
    int getElem(int index);
  }
  /**
   * Protobuf type {@code ru.ifmo.java.task.protocol.Response}
   */
  public  static final class Response extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ru.ifmo.java.task.protocol.Response)
      ResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Response.newBuilder() to construct.
    private Response(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Response() {
      elem_ = emptyIntList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Response();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Response(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              size_ = input.readInt32();
              break;
            }
            case 16: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                elem_ = newIntList();
                mutable_bitField0_ |= 0x00000001;
              }
              elem_.addInt(input.readInt32());
              break;
            }
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) != 0) && input.getBytesUntilLimit() > 0) {
                elem_ = newIntList();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                elem_.addInt(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          elem_.makeImmutable(); // C
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ru.ifmo.java.task.protocol.Protocol.internal_static_ru_ifmo_java_task_protocol_Response_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ru.ifmo.java.task.protocol.Protocol.internal_static_ru_ifmo_java_task_protocol_Response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ru.ifmo.java.task.protocol.Protocol.Response.class, ru.ifmo.java.task.protocol.Protocol.Response.Builder.class);
    }

    public static final int SIZE_FIELD_NUMBER = 1;
    private int size_;
    /**
     * <code>int32 size = 1;</code>
     * @return The size.
     */
    public int getSize() {
      return size_;
    }

    public static final int ELEM_FIELD_NUMBER = 2;
    private com.google.protobuf.Internal.IntList elem_;
    /**
     * <code>repeated int32 elem = 2;</code>
     * @return A list containing the elem.
     */
    public java.util.List<java.lang.Integer>
        getElemList() {
      return elem_;
    }
    /**
     * <code>repeated int32 elem = 2;</code>
     * @return The count of elem.
     */
    public int getElemCount() {
      return elem_.size();
    }
    /**
     * <code>repeated int32 elem = 2;</code>
     * @param index The index of the element to return.
     * @return The elem at the given index.
     */
    public int getElem(int index) {
      return elem_.getInt(index);
    }
    private int elemMemoizedSerializedSize = -1;

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (size_ != 0) {
        output.writeInt32(1, size_);
      }
      if (getElemList().size() > 0) {
        output.writeUInt32NoTag(18);
        output.writeUInt32NoTag(elemMemoizedSerializedSize);
      }
      for (int i = 0; i < elem_.size(); i++) {
        output.writeInt32NoTag(elem_.getInt(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (size_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, size_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < elem_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(elem_.getInt(i));
        }
        size += dataSize;
        if (!getElemList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        elemMemoizedSerializedSize = dataSize;
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ru.ifmo.java.task.protocol.Protocol.Response)) {
        return super.equals(obj);
      }
      ru.ifmo.java.task.protocol.Protocol.Response other = (ru.ifmo.java.task.protocol.Protocol.Response) obj;

      if (getSize()
          != other.getSize()) return false;
      if (!getElemList()
          .equals(other.getElemList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SIZE_FIELD_NUMBER;
      hash = (53 * hash) + getSize();
      if (getElemCount() > 0) {
        hash = (37 * hash) + ELEM_FIELD_NUMBER;
        hash = (53 * hash) + getElemList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ru.ifmo.java.task.protocol.Protocol.Response parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ru.ifmo.java.task.protocol.Protocol.Response parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ru.ifmo.java.task.protocol.Protocol.Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ru.ifmo.java.task.protocol.Protocol.Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ru.ifmo.java.task.protocol.Protocol.Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ru.ifmo.java.task.protocol.Protocol.Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ru.ifmo.java.task.protocol.Protocol.Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ru.ifmo.java.task.protocol.Protocol.Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ru.ifmo.java.task.protocol.Protocol.Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ru.ifmo.java.task.protocol.Protocol.Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ru.ifmo.java.task.protocol.Protocol.Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ru.ifmo.java.task.protocol.Protocol.Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ru.ifmo.java.task.protocol.Protocol.Response prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ru.ifmo.java.task.protocol.Response}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ru.ifmo.java.task.protocol.Response)
        ru.ifmo.java.task.protocol.Protocol.ResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ru.ifmo.java.task.protocol.Protocol.internal_static_ru_ifmo_java_task_protocol_Response_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ru.ifmo.java.task.protocol.Protocol.internal_static_ru_ifmo_java_task_protocol_Response_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ru.ifmo.java.task.protocol.Protocol.Response.class, ru.ifmo.java.task.protocol.Protocol.Response.Builder.class);
      }

      // Construct using ru.ifmo.java.task.protocol.Protocol.Response.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        size_ = 0;

        elem_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ru.ifmo.java.task.protocol.Protocol.internal_static_ru_ifmo_java_task_protocol_Response_descriptor;
      }

      @java.lang.Override
      public ru.ifmo.java.task.protocol.Protocol.Response getDefaultInstanceForType() {
        return ru.ifmo.java.task.protocol.Protocol.Response.getDefaultInstance();
      }

      @java.lang.Override
      public ru.ifmo.java.task.protocol.Protocol.Response build() {
        ru.ifmo.java.task.protocol.Protocol.Response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ru.ifmo.java.task.protocol.Protocol.Response buildPartial() {
        ru.ifmo.java.task.protocol.Protocol.Response result = new ru.ifmo.java.task.protocol.Protocol.Response(this);
        int from_bitField0_ = bitField0_;
        result.size_ = size_;
        if (((bitField0_ & 0x00000001) != 0)) {
          elem_.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.elem_ = elem_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ru.ifmo.java.task.protocol.Protocol.Response) {
          return mergeFrom((ru.ifmo.java.task.protocol.Protocol.Response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ru.ifmo.java.task.protocol.Protocol.Response other) {
        if (other == ru.ifmo.java.task.protocol.Protocol.Response.getDefaultInstance()) return this;
        if (other.getSize() != 0) {
          setSize(other.getSize());
        }
        if (!other.elem_.isEmpty()) {
          if (elem_.isEmpty()) {
            elem_ = other.elem_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureElemIsMutable();
            elem_.addAll(other.elem_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ru.ifmo.java.task.protocol.Protocol.Response parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ru.ifmo.java.task.protocol.Protocol.Response) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int size_ ;
      /**
       * <code>int32 size = 1;</code>
       * @return The size.
       */
      public int getSize() {
        return size_;
      }
      /**
       * <code>int32 size = 1;</code>
       * @param value The size to set.
       * @return This builder for chaining.
       */
      public Builder setSize(int value) {
        
        size_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 size = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSize() {
        
        size_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.Internal.IntList elem_ = emptyIntList();
      private void ensureElemIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          elem_ = mutableCopy(elem_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated int32 elem = 2;</code>
       * @return A list containing the elem.
       */
      public java.util.List<java.lang.Integer>
          getElemList() {
        return ((bitField0_ & 0x00000001) != 0) ?
                 java.util.Collections.unmodifiableList(elem_) : elem_;
      }
      /**
       * <code>repeated int32 elem = 2;</code>
       * @return The count of elem.
       */
      public int getElemCount() {
        return elem_.size();
      }
      /**
       * <code>repeated int32 elem = 2;</code>
       * @param index The index of the element to return.
       * @return The elem at the given index.
       */
      public int getElem(int index) {
        return elem_.getInt(index);
      }
      /**
       * <code>repeated int32 elem = 2;</code>
       * @param index The index to set the value at.
       * @param value The elem to set.
       * @return This builder for chaining.
       */
      public Builder setElem(
          int index, int value) {
        ensureElemIsMutable();
        elem_.setInt(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 elem = 2;</code>
       * @param value The elem to add.
       * @return This builder for chaining.
       */
      public Builder addElem(int value) {
        ensureElemIsMutable();
        elem_.addInt(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 elem = 2;</code>
       * @param values The elem to add.
       * @return This builder for chaining.
       */
      public Builder addAllElem(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureElemIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, elem_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 elem = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearElem() {
        elem_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ru.ifmo.java.task.protocol.Response)
    }

    // @@protoc_insertion_point(class_scope:ru.ifmo.java.task.protocol.Response)
    private static final ru.ifmo.java.task.protocol.Protocol.Response DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ru.ifmo.java.task.protocol.Protocol.Response();
    }

    public static ru.ifmo.java.task.protocol.Protocol.Response getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Response>
        PARSER = new com.google.protobuf.AbstractParser<Response>() {
      @java.lang.Override
      public Response parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Response(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Response> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Response> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ru.ifmo.java.task.protocol.Protocol.Response getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ru_ifmo_java_task_protocol_Request_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ru_ifmo_java_task_protocol_Request_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ru_ifmo_java_task_protocol_Response_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ru_ifmo_java_task_protocol_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016protocol.proto\022\032ru.ifmo.java.task.prot" +
      "ocol\"%\n\007Request\022\014\n\004size\030\001 \001(\005\022\014\n\004elem\030\002 " +
      "\003(\005\"&\n\010Response\022\014\n\004size\030\001 \001(\005\022\014\n\004elem\030\002 " +
      "\003(\005b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ru_ifmo_java_task_protocol_Request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ru_ifmo_java_task_protocol_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ru_ifmo_java_task_protocol_Request_descriptor,
        new java.lang.String[] { "Size", "Elem", });
    internal_static_ru_ifmo_java_task_protocol_Response_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ru_ifmo_java_task_protocol_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ru_ifmo_java_task_protocol_Response_descriptor,
        new java.lang.String[] { "Size", "Elem", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
